import Head from 'next/head'
import Navbar from '../components/Nav';
import Main from '../components/main';
import Image from "next/image";
import deved from '../public/YT.png'

export default function Home() {
  return (
    <div>
      <Head>

        <title>Michael | Web Development</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    
        <Navbar/>
        <Main/>
     


    </div>
  )
}
