import Head from 'next/head'
import Nav from '../components/Nav';
import Image from "next/image";
import deved from '../public/YT.png'

export default function Home() {
  return (
    <div>
      <Head>

        <title>Michael | Web Development</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <Nav/>
       <h1 className='text-5xl text-center p-10 font-noto'>Lorem ipsum dolor,  neque explicabo, in libero. Assumenda, dolorum sit?</h1>
      </main>


    </div>
  )
}
